version: '3'

services:
  app:
    container_name: my_app
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
    - db

  db:
    container_name: my_postgres
    image: postgres:11.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
