version: '3'

services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - APP_ENV=dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      bash -c "chmod +x ./wait-for-it.sh &&
        ./wait-for-it.sh db:5432 -t 30 -- fresh main.go"
  db:
    container_name: my_postgres
    image: postgres:11.1
    restart: always
    environment:
      - "TZ: Etc/UTC"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
